export default [
    {
        id: '611cea722ffae00256a83e92',
        title: 'in do commodo commodo exercitation',
        price: 1765,
        created: '2014-11-13T03:37:33',
        about: 'Id incididunt ullamco deserunt et id amet tempor do. Non culpa dolore in veniam incididunt exercitation. Aliqua officia eiusmod amet commodo aute ad qui laboris minim. Ex fugiat anim exercitation est est anim aliquip pariatur laboris est tempor qui. Labore deserunt excepteur culpa labore id ut reprehenderit nostrud.\r\n',
        views: 248,
    },
    {
        id: '611cea72a843279efb328687',
        title: 'aute duis labore minim sint',
        price: 2478,
        created: '2014-08-26T04:34:19',
        about: 'Officia deserunt dolor nisi sit ipsum ut laboris laboris. Velit nisi minim elit sint Lorem mollit aute. Labore voluptate nulla exercitation magna voluptate ut eu adipisicing esse sunt veniam quis nulla. Reprehenderit mollit quis laboris magna voluptate quis reprehenderit voluptate occaecat consectetur tempor pariatur laboris. Consequat amet culpa amet anim. Officia magna anim officia ipsum ex esse aute veniam.\r\n',
        views: 110,
    },
    {
        id: '611cea722750b432dbbecf5b',
        title: 'quis in dolore nostrud officia',
        price: 998,
        created: '2018-10-18T06:18:04',
        about: 'Anim dolor mollit amet ullamco do qui in ad tempor. Esse consectetur consectetur dolor amet eiusmod proident excepteur tempor non ullamco voluptate. Excepteur est ad aliqua aliqua non anim.\r\n',
        views: 252,
    },
    {
        id: '611cea7270d79a78ac337bb3',
        title: 'ex sunt proident in magna',
        price: 1778,
        created: '2017-05-26T10:11:15',
        about: 'Cillum mollit ex magna ipsum fugiat consequat aute. Incididunt aliqua ullamco sit Lorem sint enim ad quis cillum exercitation nulla proident tempor proident. Non id esse velit exercitation et ea do. Ut et elit elit aliquip officia minim.\r\n',
        views: 170,
    },
    {
        id: '611cea721772b5c28951deeb',
        title: 'reprehenderit mollit enim eiusmod adipisicing',
        price: 3362,
        created: '2018-04-28T04:28:17',
        about: 'Do id non laborum sit aliqua. Fugiat id qui ea ea amet ea commodo dolore in nulla. Consectetur qui minim sint consectetur commodo ullamco velit Lorem duis elit eu sunt reprehenderit culpa.\r\n',
        views: 18,
    },
];
